language: python
dist: xenial
os: linux
services:
- docker
python:
- 3.6
git:
  depth: 25
branches:
  only:
  - develop
  - "/^feature_.*/"
  - "/^main_.*/"
  - "/^bugfix_.*/"
cache:
- pip
env:
  global:
  - DO_GIT_CLONE=false
  - REPO_NAME=METplus-dev
  - REPO_NAME_lc=metplus-dev
  - CURRENT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - GH_PAGES_DIR=${HOME}/gh-pages
  - PYTHON_PACKAGES="requests"
  - OWNER_BUILD_DIR=`dirname ${TRAVIS_BUILD_DIR}`
  - DOCKER_WORK_DIR=/metplus
  - GITHUB_REPO_ORG=DTCenter
  - DOCKERHUB_DEFAULT_REPO=dtcenter/metplus-dev
  - DOCKERHUB_DEFAULT_TAGNAME=develop
  - DOCKERHUB_MET_TAGNAME=develop
  - DOCKER_DATA_DIR=/data
  - DOCKERHUB_USER_REPO="`dirname ${TRAVIS_REPO_SLUG}| awk '{print tolower($0)}'`/metplus"
  - DOCKERHUB_USER_TAGNAME=develop
  - DOCKERHUB_USE_DEFAULT=true
  - secure: SBBsZipMtxlZQutlyxN4bWcsu8e1OBuWsr6lZ8ld5+QgpZb5Evnvu1hiDjzTg82csW2+I+0SyMg3EEtCrLuX+6OcbK82JR/yj7A8zv8YyJLNwvAkPhbTXs+1xLoqSCtDZaGhSrC3aA4sQZKGzAdmmHME5kj9hkwocJVxsaxJuoao2tXft9Llc3fwsMtT59S9A638n3DkRpM8PDzL9JHYBRYriD0gJzzZKZ89U9/OhXbJwpDj5j30rt8Ia/sDQFCP3fqQiCpnUScJVPzzFRt7Ku0qZhGLA1oc6e7vXtQ2X3nnm5+wjZeSrLGDD7xjw/2osjsQGkiNN/N9Krg/rlRv5DIZsJL8d7lUG4GNXbupukL7lOBlrsCAZDSrpmHiWvl91S1jFgNw5PpgQ8hyWW9Q7u1emq4QyQs50iw3sBs5jK5qTeNCooWDMEqSkoaoz2LpBbu9oNCunvXJ0BBxYYkvAavcVQW9ykfjcrSISOfqo35geHOIBNUDBwQPxXixWk+xKIstG264P2mozkiw9EaoYWZ0FbUQXvgdCBzlT3Sd1gkbMUbk4TgBPGw2J94n6PsF6Bdwkse5gns50EYteKUKLbYMkc15OiaD2D2+QU1YZWgDuz1N7zN7Sju6K+2J4isIKMiWLJFnKoXRMLAexbwRRPoigc5QwPT8eMA4S8nuMc0=
  - secure: AdQSd2MRz40OJZEZA/i2+Xe0+QJY6hQy1ywkEwKW/1EzgntKkPL5z1NRZ+MHmjQ/w/YtKmI9xBnWP/5BB6aL63ohOtrfihgJ09E4OXXqr2QaUMzuxk8AjdDUvseqMhp97vR0VgujvCaM50n2saSMXLfym8r2+NrSFQTsfQoLbO7VF6QjJau0PSXcTnQXXkeS9ERt8eDRDqBWRpGgNindgMS488tyGM/2FA6Hukouj1Bl2u9jOkE9XlNI5ENwCvbotl8xphBcyUOJdF+XUdrEMgk2D+g0gYeCsGFaBH+1769RUDBv8Y3aF5/9LtS43kfByV3SLFCnZ/2D+m9oo5f/cOXogXbNAlFqKUwxB2I+K7CQHfpwcwZINmZ2TOnV8+GezIoSmApole6nuUKehcFpZJynkmSI7zyepNHc3ruAbkl9ZCiqItEDXfQnwtsiWJoFa6hMGeVg4nE4RMlUKtBMbuYpEcAk+svbt9Dff66cH/CT5g3NfZuKd0HlLZSz12cer7G3uY1vcS2fCRs0IVBrKCoiIgJL4Jo5dKP/ufZsss1UJeMMoUtZRUe510uVbBhYn47wGTF63SenDjvS6JdtOG/ZTJQ55VLmbG6hQEhznTuIZ2kkiR8ZW0V1sMLyppV/CvL5kiRma928wj3NqTHh5K6zHdRw2RYeGBgLNHOLCtc=
script:
- pwd
install:
- if [ ! -z "$PYTHON_PACKAGES" ]; then pip install --upgrade pip; pip install $PYTHON_PACKAGES;
  fi
- pip list
before_script:
- if [[ ${DOCKERHUB_USE_DEFAULT} == true ]]; then export DOCKERHUB_TAG=${DOCKERHUB_DEFAULT_REPO}:${DOCKERHUB_DEFAULT_TAGNAME};
  else export DOCKERHUB_TAG=${DOCKERHUB_USER_REPO}:${DOCKERHUB_USER_TAGNAME}; fi;
- echo ${DOCKERHUB_TAG}; echo ${GITHUB_REPO_ORG}; echo ${TRAVIS_REPO_SLUG}; echo ${TRAVIS_BUILD_DIR};
  echo ${OWNER_BUILD_DIR};
jobs:
  allow_failures:
  - stage: Documentation
  include:
  - stage: Documentation
    before_install: export PYTHON_PACKAGES="$PYTHON_PACKAGES sphinx_rtd_theme doc8"
    script:
    - doc8 docs/index.rst docs/Users_Guide/ docs/Contributors_Guide/
  - stage: Docker Setup
    name: Update Data Volumes
    before_install: export PYTHON_PACKAGES="$PYTHON_PACKAGES bs4 python-dateutil"
    script:
    - echo "$DOCKER_PASSWORD" $DOCKER_PASSWORD
    - echo "$DOCKER_USERNAME" $DOCKER_USERNAME
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/docker_update_data_volumes.py"
  - name: Get METplus Image
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/docker_setup.sh"
  - stage: Tests
    name: Pytest Unit Tests
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_unit.sh"
  - name: Use Case Tests - met_tool_wrapper
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_met_tool_wrapper.sh"
  - name: Use Case Tests - data_assimilation
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_data_assimilation.sh"
  - name: Use Case Tests - cryosphere
    script:
    - travis_wait 30 ${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh
      --cryosphere
  - name: Use Case Tests - convection_allowing_models
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --convection_allowing_models"
  - name: Use Case Tests - climate
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --climate"
  - name: Use Case Tests - medium_range1
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --medium_range1"
  - name: Use Case Tests - medium_range2
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --medium_range2"
  - name: Use Case Tests - medium_range3
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_medium_range3.sh"
  - name: Use Case Tests - precipitation
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --precipitation"
  - name: Use Case Tests - s2s, space_weather, tc_and_extra_tc
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --s2s
      --space_weather --tc_and_extra_tc"
