language: python
dist: xenial
os: linux
services:
- docker
python:
- 3.6
git:
  depth: 25
branches:
  only:
  - develop
  - "/^feature_.*/"
  - "/^main_.*/"
  - "/^bugfix_.*/"
cache:
- pip
env:
  global:
  - DO_GIT_CLONE=false
  - REPO_NAME=METplus-dev
  - REPO_NAME_lc=metplus-dev
  - CURRENT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - GH_PAGES_DIR=${HOME}/gh-pages
  - PYTHON_PACKAGES="requests"
  - OWNER_BUILD_DIR=`dirname ${TRAVIS_BUILD_DIR}`
  - DOCKER_WORK_DIR=/metplus
  - GITHUB_REPO_ORG=DTCenter
  - DOCKERHUB_DEFAULT_REPO=dtcenter/metplus-dev
  - DOCKERHUB_DEFAULT_TAGNAME=develop
  - DOCKERHUB_MET_TAGNAME=develop
  - DOCKER_DATA_DIR=/data
  - DOCKERHUB_USER_REPO="`dirname ${TRAVIS_REPO_SLUG}| awk '{print tolower($0)}'`/metplus"
  - DOCKERHUB_USER_TAGNAME=develop
  - DOCKERHUB_USE_DEFAULT=true
  - secure: jLMFVWgRIYmJFTWiAkSGMkYfKwv15aDgq98loF8uUfDrH0YS4CFuQOgMz2KysoY6U5P6VJt+kgDs1eNS/rA8SrGGLe7bbqggEXZ9xXi7EBWhBIz42q5BywGcea3IRCYiTugjfl2z8StYfh5iv2QfANgARmWF5ib5zuyxKV+Q68XGATt7kXyXDSSXPaXUhLzmu1qR1iSGG7kOz/xE41VFTPk9HPvQ0SvGAFczW4LyJ8+Hl1qY2RcYz4O2dAqNIV29A4zGwuqgBEaIfCtUld02aCO/4KOvXPHxok1z7zBWPZAlaLhsrMANN8ApA+6Cxnolfm0Hm09qU9zqkDBMPREbDgty0tuaF8FkWUYdMfxMYIwq6EcT8kQSJxzIsfbl4L2A8TU+KjDKSznpxAfN9j2dYaxRAzm5c3ke+wqSJc14LMW4UkEG/fgxG30/+HARrmrNoYS9RAiqz9AsIVJ+bKcFDnOMKM/npl6xrwAMPwh6stNleGYqFrm3QQ/JNfkC40qhy9aAtElwQ7qcYlQOGvVLzZ2/iEbVlStul74d13O6Ug2TLoSNU/5SztGtqDg/Sy4N3kMylNQ3Ji/PgKUd2lVdrkQKTvoTxFMZSnEPEfpRbYJl1mhrey8eOGGZJi5aYTs5xFoOBL+awCF/8kZee6FI09NI7yGIKbZ9I1CwA8DIo38=
  - secure: UIAEYeTFfkgjy5Sg4Ejkr7aISU4Pr45yiXxlvCcmoctUT7vi4DFM3WXSg8N6ZaHxiBMu3c1OaeHkTOuSHQgNs40plSY/THWDqWbdWRfbI2gjN7hWO9h/G8Cb3JuXQewQe+6F4pLJ/Wfp4xhPoBkjZQFe+cuvvzDMjNp36iuYZNA5Xek95C3HgmhmEudG3W210otplmtB/E89CGm0hQorz1pgOkZVmdvF+Kj+Nz5pzWzT5ZIaNKLcfIk+/5iID5Ktkz3s23+ZUUBfGT2Q7uDqwIkV6g7hMAoADZpsS+5m5ZHK/WfrSxxGvr998Utz/blyrtrUQ7Y3Go/sNq5SQUlHvoM4chkSgnWlosa792fCADA+YHPDuFDyB/TZmcZyIc+5Ou+klkednlu+h5UIeza/aIOQydmerArMWbQuz9DW3uH83mAv1jJT97XCcfYgMbi1T76r6QqVosx6HSPWifGN3AnDhU5dQr+CVLTua/e+eCDXIfBMKBEtkwFtvbd/KMlcDdygSggxWbA35/wOhC/i6D3CzhrycisKHtZR6nayr6aEpDAR4ylToIlrk5lT+rou8blUHA+mPfjCroVkY5tWLgKeGYpDb3ztpebrmKmt8f/U1cf4Obia3wOdJU1NuT6injoTmbMvphxKLRsWaGQc9IiNBdEt20dAmJk9d31GYmA=
script:
- pwd
install:
- if [ ! -z "$PYTHON_PACKAGES" ]; then pip install --upgrade pip; pip install $PYTHON_PACKAGES;
  fi
- pip list
before_script:
- if [[ ${DOCKERHUB_USE_DEFAULT} == true ]]; then export DOCKERHUB_TAG=${DOCKERHUB_DEFAULT_REPO}:${DOCKERHUB_DEFAULT_TAGNAME};
  else export DOCKERHUB_TAG=${DOCKERHUB_USER_REPO}:${DOCKERHUB_USER_TAGNAME}; fi;
- echo ${DOCKERHUB_TAG}; echo ${GITHUB_REPO_ORG}; echo ${TRAVIS_REPO_SLUG}; echo ${TRAVIS_BUILD_DIR};
  echo ${OWNER_BUILD_DIR};
jobs:
  allow_failures:
  - stage: Documentation
  include:
  - stage: Documentation
    before_install: export PYTHON_PACKAGES="$PYTHON_PACKAGES sphinx_rtd_theme doc8"
    script:
    - doc8 docs/index.rst docs/Users_Guide/ docs/Contributors_Guide/
  - stage: Docker Setup
    name: Update Data Volumes
    before_install: export PYTHON_PACKAGES="$PYTHON_PACKAGES bs4 python-dateutil"
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/docker_update_data_volumes.py"
  - name: Get METplus Image
    script:
    - echo "$DOCKER_PASSWORD" $DOCKER_PASSWORD
    - echo "$DOCKER_USERNAME" $DOCKER_USERNAME
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/docker_setup.sh"
  - stage: Tests
    name: Pytest Unit Tests
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_unit.sh"
  - name: Use Case Tests - met_tool_wrapper
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_met_tool_wrapper.sh"
  - name: Use Case Tests - data_assimilation
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_data_assimilation.sh"
  - name: Use Case Tests - cryosphere
    script:
    - travis_wait 30 ${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh
      --cryosphere
  - name: Use Case Tests - convection_allowing_models
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --convection_allowing_models"
  - name: Use Case Tests - climate
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --climate"
  - name: Use Case Tests - medium_range1
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --medium_range1"
  - name: Use Case Tests - medium_range2
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --medium_range2"
  - name: Use Case Tests - medium_range3
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_medium_range3.sh"
  - name: Use Case Tests - precipitation
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --precipitation"
  - name: Use Case Tests - s2s, space_weather, tc_and_extra_tc
    script:
    - "${TRAVIS_BUILD_DIR}/ci/travis_jobs/test_use_cases_model_applications.sh --s2s
      --space_weather --tc_and_extra_tc"
